/**
 * 插件 dsh-bull-review（历史牛市复盘）· 轮次档案（结论性内容）
 *
 * 2000 年以来「机构抱团 → 瓦解」牛市的标准化拆解，硬编码于此 —— 历史复盘是不可变结论，
 * 不做运行时拼装。定位：**不预测下一轮牛市，也不承诺预测崩盘时点**；价值在四阶段拆解、
 * 多因子错配画像与可复用风险模式（对标豆包复盘框架 + 招商证券「A 股四轮抱团」研究口径）。
 *
 * 事件时间线每轮 10–14 条，按五类标注（龙头动向 / 国内政策 / 海外环境 / 资金情绪 / 产业业绩），
 * 重点覆盖：中军领涨与见顶时点、多杀多踩踏、国内外政策与流动性拐点。
 * ⚠️ 本轮科技 AI 的 2025H2 之后事件来自用户复盘口径（豆包对话 2026-09-20），随行情推进补录。
 * ⚠️ 全部文字为复盘观点，仅供参考，不构成投资建议；
 * 区间涨幅 / 回撤等数字由 `judge.ts` 从月 K 回算，这里只写定性与时间窗。
 */
import type { ReviewRoundMeta } from './types';

/** 全部轮次（数组顺序即时间轴顺序） */
export const BULL_ROUNDS: readonly ReviewRoundMeta[] = [
  {
    id: 'golden-five',
    name: '五朵金花',
    short: '03–04',
    indexSymbol: 'sh000001',
    indexName: '上证指数',
    roundType: '机构雏形',
    collapseType: 'C',
    collapseLabel: 'C 类·阴跌新低',
    status: '已瓦解',
    window: { start: '2003-01', peak: '2004-04', end: '2005-06' },
    span: '2003.01 – 2005.06',
    mainline: '汽车 / 钢铁 / 石化 / 电力 / 银行',
    midCaps: '长安汽车、宝钢股份、扬子石化、招商银行',
    macro: '重工业化加速 · QFII 引入价值投资理念 · 公募基金起步',
    rival: '无（指数整体走熊中的结构性行情）',
    stages: [
      { name: '启动期', start: '2003-01', end: '2003-10', tone: 's1', desc: '资金开始向「五朵金花」集中，价值投资第一次抱团实验' },
      { name: '发酵主升', start: '2003-10', end: '2004-04', tone: 's2', desc: '重工业化逻辑强化，核心资产逆势创新高' },
      { name: '高潮鱼尾', start: '2004-04', end: '2004-09', tone: 's3', desc: '宏观调控信号已出，抱团仍在自我强化' },
      { name: '退潮期', start: '2004-09', end: '2005-06', tone: 's4', desc: '加息 + 铁本事件，盈利预期证伪，指数创新低' },
    ],
    events: [
      { date: '2002.11', title: 'QFII 试行办法出台', detail: '外资定价权叙事的制度起点', kind: 'expected', category: 'policy' },
      { date: '2003.01', title: '基金四季报集中披露重仓', detail: '公募首次齐刷刷重仓钢铁 / 汽车 / 石化，「五朵金花」成型', kind: 'landed', category: 'funds' },
      { date: '2003.04', title: '非典疫情冲击市场', detail: '指数急跌，但重工业盈利未受根本影响，抱团反而强化', kind: 'landed', category: 'overseas' },
      { date: '2003.05', title: '首批 QFII 资格落地（瑞银 / 野村）', detail: '7 月瑞银下单买入宝钢等，价值投资获得外部背书', kind: 'landed', category: 'overseas' },
      { date: '2003.06', title: '长安汽车业绩爆发', detail: '中报预增，汽车股率先领涨，成为第一朵「金花」', kind: 'landed', category: 'leader' },
      { date: '2003.10', title: '十六届三中全会', detail: '重工业化逻辑进一步强化，五朵金花主升', kind: 'landed', category: 'policy' },
      { date: '2004.02', title: '「国九条」发布', detail: '国务院首份资本市场顶层文件，情绪与政策双顶助推', kind: 'landed', category: 'policy' },
      { date: '2004.02', title: '长安汽车率先见顶', detail: '车市价格战开启、销量增速回落，龙头最先走弱；宝钢 / 扬子石化 3–4 月相继见顶', kind: 'landed', category: 'leader' },
      { date: '2004.04', title: '宏观调控升级', detail: '提准 0.5 个百分点 + 发改委严控钢铁 / 电解铝 / 水泥投资；「铁本事件」查处，盈利预期直接证伪', kind: 'landed', category: 'policy' },
      { date: '2004.05', title: '汽车销量转负增长', detail: '产业数据坐实景气拐点，五朵金花集体进入退潮', kind: 'landed', category: 'sector' },
      { date: '2004.H2', title: '基金减仓踩踏', detail: '超配机构集中调仓，抱团股互相杀跌（早期「多杀多」）', kind: 'landed', category: 'funds' },
      { date: '2004.10', title: '九年来的首次加息', detail: '一年期存贷款利率上调 0.27 个百分点，估值与盈利双杀', kind: 'landed', category: 'policy' },
      { date: '2005.04', title: '股权分置改革试点启动', detail: '对价不确定性引发恐慌，指数探至 998，本轮结构抱团彻底终结', kind: 'landed', category: 'policy' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: true },
      { dimension: '中军走势', diverged: false },
      { dimension: '媒体舆论', diverged: true },
      { dimension: '机构行为', diverged: false },
      { dimension: '散户情绪', diverged: false },
    ],
    trigger: '宏观调控 + 加息，盈利预期证伪',
    review:
      '驱动：重工业化 + 价值投资理念；瓦解：行政紧缩直接打掉盈利预期，属于「逻辑证伪型」。' +
      '意义：基金业的第一次抱团与第一次瓦解，此后「抱团—瓦解」的模式反复重演。',
  },
  {
    id: 'gaint-reform',
    name: '股改大牛市（大金融）',
    short: '05–07',
    indexSymbol: 'sh000001',
    indexName: '上证指数',
    roundType: '机构抱团',
    collapseType: 'C',
    collapseLabel: 'C 类·权重阴跌',
    status: '已瓦解',
    window: { start: '2005-06', peak: '2007-10', end: '2008-10' },
    span: '2005.06 – 2008.10',
    mainline: '金融 / 地产（招商银行、万科、中信证券）',
    midCaps: '浦发银行、保利地产、辽宁成大',
    macro: '股权分置改革 · 汇改升值 · 公募大扩容「储蓄搬家」',
    rival: '无（独龙主线，全市场普涨）',
    stages: [
      { name: '启动期', start: '2005-06', end: '2006-08', tone: 's1', desc: '股改对价 + 价值重估，指数自 998 缓缓抬升' },
      { name: '发酵主升', start: '2006-08', end: '2007-05', tone: 's2', desc: '储蓄搬家，基金发行爆款频出，申购正反馈成形' },
      { name: '高潮鱼尾', start: '2007-05', end: '2007-10', tone: 's3', desc: '全民炒股，估值与换手双极值，「黄金十年」叙事出圈' },
      { name: '退潮期', start: '2007-10', end: '2008-10', tone: 's4', desc: '连续加息加准 + 大小非解禁 + 金融危机，权重阴跌不止' },
    ],
    events: [
      { date: '2005.04', title: '股权分置改革试点启动', detail: '三一重工打样，制度红利确立本轮牛市的地基', kind: 'expected', category: 'policy' },
      { date: '2005.06', title: '上证 998.23 历史大底', detail: '「千点论」情绪极致后反转', kind: 'landed', category: 'funds' },
      { date: '2005.07', title: '汇改启动', detail: '人民币进入升值通道，金融地产成为升值受益主线', kind: 'landed', category: 'policy' },
      { date: '2005.H2', title: 'G 股行情铺开', detail: 'QFII / 保险 / 社保资金批量入市，机构定价权确立', kind: 'landed', category: 'funds' },
      { date: '2006.06', title: '招行、万科率先创新高', detail: '金融地产中军领涨主线确立，行情由普涨转向抱团', kind: 'landed', category: 'leader' },
      { date: '2006 全年', title: '储蓄搬家第一波', detail: '偏股基金全年发行约 4000 亿，申购正反馈启动', kind: 'landed', category: 'funds' },
      { date: '2007.05', title: '「5·30」印花税上调至 3‰', detail: '垃圾股崩盘而蓝筹续涨——资金向中军进一步集中，抱团反而强化', kind: 'landed', category: 'policy' },
      { date: '2007 上半年', title: '开户狂潮', detail: '日均新开户数十万，「基民」「股民」出圈，散户借基金入市', kind: 'landed', category: 'funds' },
      { date: '2007.08', title: '美国次贷危机首发', detail: '海外剧烈动荡，A 股一度免疫续涨——最后的疯狂', kind: 'landed', category: 'overseas' },
      { date: '2007.10', title: '中军集体见顶', detail: '招行 / 万科 / 中信证券同月见顶；公募 Q3 仓位约 90%，金融地产超配历史峰值', kind: 'landed', category: 'leader' },
      { date: '2007.10.16', title: '6124.04 历史顶', detail: '「黄金十年」「万点论」出圈即顶部，估值 / 换手 / 申购三极值', kind: 'landed', category: 'funds' },
      { date: '2007 全年', title: '6 次加息 + 10 次提准', detail: '紧缩贯穿主升全程，流动性拐点最终压垮估值', kind: 'landed', category: 'policy' },
      { date: '2008.01', title: '大小非解禁洪峰', detail: '全年解禁市值超 3 万亿，筹码供给压垮申购端', kind: 'landed', category: 'funds' },
      { date: '2008 全年', title: '权重阴跌 + 赎回踩踏', detail: '大金融几乎不跌停、以阴跌完成见顶（C 类）；基金遭遇巨额赎回被迫杀跌，多杀多贯穿全年', kind: 'landed', category: 'funds' },
      { date: '2008.09', title: '雷曼破产', detail: '全球金融危机全面爆发，10.28 指数见 1664.93，一年跌去七成', kind: 'landed', category: 'overseas' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: false },
      { dimension: '中军走势', diverged: true },
      { dimension: '媒体舆论', diverged: true },
      { dimension: '机构行为', diverged: true },
      { dimension: '散户情绪', diverged: true },
    ],
    trigger: '连续紧缩 + 大小非解禁 + 全球金融危机',
    review:
      '超大权重抱团的典型：涨跌停看板几乎失效（大金融常年无涨跌停），瓦解信号只体现在权重 K 线、信贷与流动性。' +
      '998 → 6124 → 1664，指数一年跌去七成，是「C 类阴跌见顶」的极致样本。',
  },
  {
    id: 'four-trillion',
    name: '四万亿周期牛',
    short: '08–10',
    indexSymbol: 'sh000001',
    indexName: '上证指数',
    roundType: '政策驱动',
    collapseType: 'B',
    collapseLabel: 'B 类·中军先滞涨',
    status: '已瓦解',
    window: { start: '2008-11', peak: '2009-08', end: '2010-07' },
    span: '2008.11 – 2010.07（白酒结构抱团延续至 2012.7）',
    mainline: '有色 / 煤炭 / 地产 → 白酒 / 医药',
    midCaps: '江西铜业、西山煤电、贵州茅台',
    macro: '四万亿信贷 · 通胀上行 · 流动性泛滥',
    rival: '消费（白酒）2010 年起接力走独立行情',
    stages: [
      { name: '启动期', start: '2008-11', end: '2009-02', tone: 's1', desc: '信贷井喷，强周期估值修复' },
      { name: '发酵主升', start: '2009-02', end: '2009-08', tone: 's2', desc: '「煤飞色舞」，翻倍行情' },
      { name: '高潮鱼尾', start: '2009-08', end: '2009-12', tone: 's3', desc: '7 月信贷骤降，高位放量滞涨' },
      { name: '退潮期', start: '2009-12', end: '2010-07', tone: 's4', desc: '信贷收缩 + IPO 重启，指数阴跌五年序幕' },
    ],
    events: [
      { date: '2008.11', title: '四万亿投资计划出台', detail: '11.27 再降息 108 个基点，政策强刺激一步到位', kind: 'landed', category: 'policy' },
      { date: '2008.12', title: '信贷井喷', detail: '单月新增贷款 7700 亿起步，有色煤炭率先反弹领涨', kind: 'landed', category: 'funds' },
      { date: '2009.01', title: '十大产业振兴规划', detail: '汽车钢铁领衔密集出台，强周期盈利预期快速修复', kind: 'landed', category: 'policy' },
      { date: '2009.H1', title: '上半年新增信贷 7.37 万亿', detail: '流动性泛滥推升「煤飞色舞」，江西铜业等翻数倍', kind: 'landed', category: 'leader' },
      { date: '2009.06', title: 'IPO 重启', detail: '新股供给恢复，市场流动性边际收紧的第一个信号', kind: 'landed', category: 'policy' },
      { date: '2009.07', title: '7 月信贷骤降至 3559 亿', detail: '较 6 月 1.53 万亿断崖；7.29 中国建筑 IPO 冻资叠加重启央票，单日 -5%', kind: 'landed', category: 'policy' },
      { date: '2009.08', title: '3478.01 见顶', detail: '高位放量滞涨，强周期中军率先走弱（B 类特征）', kind: 'landed', category: 'leader' },
      { date: '2009.H2', title: '周期多杀多', detail: '超配机构集中撤出强周期，调仓涌向大消费——下一轮结构主线的起点', kind: 'landed', category: 'funds' },
      { date: '2009.10', title: '创业板开板', detail: '首批 28 家上市，资金分流 + 新战场开启', kind: 'landed', category: 'policy' },
      { date: '2010.04', title: '地产「国十条」调控', detail: '地产链彻底退潮，周期抱团再无回头', kind: 'landed', category: 'policy' },
      { date: '2010.07', title: '上证 2319 阶段低点', detail: '指数阴跌，但白酒 / 医药走出独立结构牛', kind: 'landed', category: 'funds' },
      { date: '2010–2012', title: '白酒结构抱团接力', detail: '茅台批价 800 → 2000 元，2012.7 见顶；主线从周期切换到消费', kind: 'landed', category: 'leader' },
      { date: '2012.11', title: '塑化剂事件', detail: '酒鬼酒检出塑化剂，白酒信任危机爆发', kind: 'landed', category: 'sector' },
      { date: '2012.12', title: '「八项规定」出台', detail: '政务需求一夜归零，白酒逻辑证伪、多杀多腰斩——结构抱团终结', kind: 'landed', category: 'policy' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: true },
      { dimension: '中军走势', diverged: false },
      { dimension: '媒体舆论', diverged: false },
      { dimension: '机构行为', diverged: false },
      { dimension: '散户情绪', diverged: true },
    ],
    trigger: '信贷收缩 + IPO 重启；白酒最终被塑化剂与限制三公消费终结',
    review:
      '政策驱动型：启动与瓦解都由信贷量一步定调，「放量不涨」是本轮最提前的信号。' +
      '主线瓦解后消费（白酒医药）接力走出 2010–2012 的结构抱团，说明一轮大级别退潮里往往孕育下一轮结构主线。',
  },
  {
    id: 'tmt-leverage',
    name: 'TMT「互联网+」杠杆牛',
    short: '12–15',
    indexSymbol: 'sz399006',
    indexName: '创业板指',
    roundType: '机构抱团 + 杠杆',
    collapseType: 'B',
    collapseLabel: 'B 类·中军先滞涨',
    status: '已瓦解',
    window: { start: '2012-12', peak: '2015-06', end: '2015-09' },
    span: '2012.12 – 2015.09',
    mainline: '传媒 / 计算机 + 中小创（互联网+）',
    midCaps: '东方财富、乐视网、全通教育（并购外延代表）',
    macro: '移动互联网产业周期 · 并购重组外延 · 场外配资正反馈',
    rival: '2014H2 大盘蓝筹短暂分流（中字头行情）',
    stages: [
      { name: '启动期', start: '2012-12', end: '2013-09', tone: 's1', desc: '创业板率先走出结构性牛市，钱荒砸出的 1849 成为底' },
      { name: '发酵主升', start: '2013-09', end: '2015-03', tone: 's2', desc: '并购增厚业绩 + 配资加杠杆，双轮正反馈' },
      { name: '高潮鱼尾', start: '2015-03', end: '2015-06', tone: 's3', desc: '「神创板」：市梦率定价，全通教育登顶 A 股第一高价股' },
      { name: '退潮期', start: '2015-06', end: '2015-09', tone: 's4', desc: '清理场外配资 → 三轮股灾 + 熔断' },
    ],
    events: [
      { date: '2012.11', title: 'IPO 空窗期开始', detail: '新股停发一年余，小票筹码供给冻结，存量抱团易涨', kind: 'landed', category: 'policy' },
      { date: '2012.12', title: '创业板 585.44 历史大底', detail: '移动互联网渗透率加速，TMT 估值修复启动', kind: 'landed', category: 'sector' },
      { date: '2013 全年', title: '手游 / 影视并购潮', detail: '华谊兄弟年涨约 3 倍，掌趣科技并购神话——外延增长叙事确立', kind: 'landed', category: 'leader' },
      { date: '2013.06', title: '钱荒', detail: '隔夜 SHIBOR 飙至 13.44%，上证探 1849.65；主板熊市见底而创业板逆势走强——主线独立的标志', kind: 'landed', category: 'policy' },
      { date: '2013.08', title: '上海自贸区获批', detail: '题材轮动加剧，资金加速向中小创集中', kind: 'landed', category: 'policy' },
      { date: '2014.H2', title: '中字头行情分流', detail: '一带一路 + 南北车合并，大盘蓝筹暴动、创业板横盘半年——主线内部第一次大分歧', kind: 'landed', category: 'policy' },
      { date: '2014.11', title: '两年来首次降息', detail: '11–12 月上证暴涨四成；杠杆资金（两融 + 配资）全面入场', kind: 'landed', category: 'policy' },
      { date: '2015.01', title: '两融罚单「1·19」', detail: '券商股集体跌停，资金从蓝筹回流创业板——抱团主线切换完成', kind: 'landed', category: 'policy' },
      { date: '2015.H1', title: '场外配资失控', detail: '规模约 1–1.5 万亿，6.18 融资余额峰值 2.27 万亿，杠杆正反馈到顶', kind: 'landed', category: 'funds' },
      { date: '2015.03', title: '龙头鱼尾信号', detail: '全通教育 348 元登顶 A 股第一高价股后迅速跌出前十；安硕信息 474 元、乐视网 179 元 5 月相继见顶——中军领涨到中军见顶只差一个季度', kind: 'landed', category: 'leader' },
      { date: '2015.04', title: '「4000 点才是牛市起点」', detail: '官媒背书把散户情绪推向极致，舆论顶点', kind: 'landed', category: 'funds' },
      { date: '2015.05', title: '高位巨震', detail: '5.28 单日 -6.5%，筹码松动、分歧加剧的第一声警报', kind: 'landed', category: 'funds' },
      { date: '2015.06', title: '清理场外配资', detail: '6.12 上证 5178 见顶当天监管清配；杠杆链断裂 → 6.26 创业板 -9% 千股跌停、7.8 约半数个股停牌——多杀多 + 强平踩踏的极致', kind: 'landed', category: 'policy' },
      { date: '2015.08', title: '二次探底', detail: '8.24 单日 -8.49%「黑色星期一」；9.15 创业板 1779，较顶点 -56%', kind: 'landed', category: 'funds' },
      { date: '2016.01', title: '熔断', detail: '四天四次熔断后暂停机制，1.27 上证 2638.30，本轮杠杆牛彻底清算', kind: 'landed', category: 'policy' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: true },
      { dimension: '中军走势', diverged: true },
      { dimension: '媒体舆论', diverged: true },
      { dimension: '机构行为', diverged: true },
      { dimension: '散户情绪', diverged: true },
    ],
    trigger: '清理场外配资去杠杆，杠杆链断裂',
    review:
      '「机构抱团 + 杠杆」双驱动：涨跌停指标在中段有效，崩塌由去杠杆触发。' +
      '与 2021 核心资产同构的是「申购正反馈」，不同在杠杆把瓦解从阴跌变成雪崩——三轮股灾 + 熔断只用了半年。',
  },
  {
    id: 'core-asset',
    name: '核心资产·白酒抱团',
    short: '16–21',
    indexSymbol: 'sh000300',
    indexName: '沪深300',
    roundType: '机构抱团',
    collapseType: 'C',
    collapseLabel: 'C 类·权重阴跌',
    status: '已瓦解',
    window: { start: '2016-01', peak: '2021-02', end: '2022-04' },
    span: '2016.01 – 2022.04',
    mainline: '白酒 / 医药 / 消费「茅指数」',
    midCaps: '贵州茅台、五粮液、恒瑞医药、中国中免',
    macro: '外资定价权 · 龙头集中 · 2020 基金发行超级周期（约 3 万亿）',
    rival: '2020H2 起新能源接力分流（宁组合）',
    stages: [
      { name: '启动期', start: '2016-01', end: '2017-05', tone: 's1', desc: '深港通 + 外资持续买入，白马价值重估（漂亮 50）' },
      { name: '发酵主升', start: '2017-05', end: '2020-06', tone: 's2', desc: '2018 中途回撤未破逻辑，公募持续超配，集中度抬升' },
      { name: '高潮鱼尾', start: '2020-06', end: '2021-02', tone: 's3', desc: '爆款基金月发千亿，「茅」字出圈，估值分位历史极值' },
      { name: '退潮期', start: '2021-02', end: '2022-04', tone: 's4', desc: '春节后美债利率飙升杀估值，权重阴跌一年' },
    ],
    events: [
      { date: '2014.11', title: '沪港通开通', detail: '外资定价权的制度铺垫（2016.12 深港通接续）', kind: 'landed', category: 'policy' },
      { date: '2016–2017', title: '外资持续流入白马', detail: '2017 年陆股通净买入约 2000 亿创当时纪录，茅台 / 格力 / 恒瑞率先领涨', kind: 'landed', category: 'funds' },
      { date: '2017.06', title: 'A 股纳入 MSCI', detail: '国际化叙事落地，「核心资产」定价体系确立', kind: 'landed', category: 'overseas' },
      { date: '2017.09', title: '爆款基金初现', detail: '东方红系列单日售罄配售，公募话语体系回流', kind: 'landed', category: 'funds' },
      { date: '2017.11', title: '官媒提示茅台', detail: '新华社发文理性看待茅台股价 + 集团限价令——短期回调但逻辑未破', kind: 'landed', category: 'policy' },
      { date: '2018.10', title: '贸易摩擦 + 茅台罕见跌停', detail: '去杠杆叠加外部冲击，茅台 10.29 跌停至 509；中途回撤近腰斩但逻辑未破——主升中途最大考验', kind: 'landed', category: 'leader' },
      { date: '2018.10', title: '高层集体喊话稳市场', detail: '10.19 刘鹤及一行两会表态，2449 确认政策底', kind: 'landed', category: 'policy' },
      { date: '2019 全年', title: '外资净流入 3500 亿创新高', detail: '消费 / 医药主升，「核心资产」成为公募统一话术', kind: 'landed', category: 'funds' },
      { date: '2020.03', title: '全球疫情崩盘', detail: '美股十天内三次熔断，核心资产急跌后 V 型反转——放水下的抱团加速', kind: 'landed', category: 'overseas' },
      { date: '2020.07', title: '基金发行超级周期', detail: '单月新发约 3000 亿；公募重仓前 50 集中度走向历史峰值', kind: 'landed', category: 'funds' },
      { date: '2020.Q4', title: '北向开始悄然撤退', detail: '指数续创新高而外资净卖出核心资产——「价涨资金走」的经典背离', kind: 'landed', category: 'funds' },
      { date: '2021.01', title: '申购端正反馈到顶', detail: '单月偏股新发约 4900 亿；「坤坤」「兰兰」出圈，张坤基金限购——情绪顶点标志', kind: 'landed', category: 'funds' },
      { date: '2021.02', title: '茅台 2627.88 见顶 + 美债飙升', detail: '2.10 盘中历史高点；春节后 10 年期美债利率破 1.6%，估值锚坍塌，核心资产十余日 -20%+', kind: 'landed', category: 'overseas' },
      { date: '2021.H2', title: '公募多杀多', detail: '基民赎回负反馈担忧发酵，机构从白酒切向新能源；8.20 茅台跌穿 1550，较顶点 -41%', kind: 'landed', category: 'funds' },
      { date: '2022.01', title: '加息 + 俄乌 + 封控三连击', detail: '美联储 3 月加息落地、俄乌开战、上海封控，4.27 沪深300 见阶段低点，本轮退潮收尾', kind: 'landed', category: 'overseas' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: false },
      { dimension: '中军走势', diverged: true },
      { dimension: '媒体舆论', diverged: true },
      { dimension: '机构行为', diverged: true },
      { dimension: '散户情绪', diverged: true },
    ],
    trigger: '美债利率上行杀估值 + 申购正反馈逆转',
    review:
      '错配画像（鱼尾 2020H2）：涨停几乎全来自三四线小酒，茅台不涨停但公募仍在超配；北向 2020Q4 起净卖出，与「黄金赛道」舆论背离。' +
      '看板预警能力差的典型——中军不跌停、以阴跌完成见顶（C 类），逃顶依据只有中军趋势、成交额与利率。',
  },
  {
    id: 'ning-combo',
    name: '新能源抱团（宁组合）',
    short: '20–22',
    indexSymbol: 'sz399006',
    indexName: '创业板指',
    roundType: '机构抱团·产业景气',
    collapseType: 'B',
    collapseLabel: 'B 类·产业逻辑松动',
    status: '已瓦解',
    window: { start: '2020-07', peak: '2021-11', end: '2022-04' },
    span: '2020.07 – 2022.04',
    mainline: '电新 / 锂电 / 光伏',
    midCaps: '宁德时代、隆基绿能、亿纬锂能',
    macro: '渗透率爆发 · 碳中和政策 · 接棒核心资产的增量抱团',
    rival: '消费（茅指数）同期崩塌，资金迁移而来',
    stages: [
      { name: '启动期', start: '2020-07', end: '2020-12', tone: 's1', desc: '景气验证：排产与价格持续超预期' },
      { name: '发酵主升', start: '2020-12', end: '2021-07', tone: 's2', desc: '「有锂走遍天下」，上游资源暴涨' },
      { name: '高潮鱼尾', start: '2021-07', end: '2021-11', tone: 's3', desc: '中军滞涨、板块成交不再新高、题材乱飞' },
      { name: '退潮期', start: '2021-11', end: '2022-04', tone: 's4', desc: '产能过剩预期 + 美联储加息，大级别回调' },
    ],
    events: [
      { date: '2020.07', title: '景气验证启动', detail: '动力电池排产持续超预期，宁德时代单月大涨，接棒白酒成为公募新抱团', kind: 'landed', category: 'sector' },
      { date: '2020.08', title: '创业板注册制落地', detail: '涨跌幅放宽至 20%，题材弹性放大，增量资金聚焦创业板', kind: 'landed', category: 'policy' },
      { date: '2020.09', title: '「3060」双碳目标宣布', detail: '联合国大会承诺碳中和，长周期产业叙事确立', kind: 'landed', category: 'policy' },
      { date: '2020.11', title: '新能源车产业规划落地', detail: '《2021–2035 规划》发布，11 月销量同比 +104%，渗透率陡峭上行', kind: 'landed', category: 'sector' },
      { date: '2021.H1', title: '「有锂走遍天下」', detail: '碳酸锂价格启动上行，上游锂矿 / 电解液 / 六氟领涨，板块扩散至全产业链', kind: 'landed', category: 'leader' },
      { date: '2021.07', title: '宁德时代盘中 582 见顶区域', detail: '中军最先滞涨；板块成交额占全市场比例同步见顶回落——「放量不涨」警报', kind: 'landed', category: 'leader' },
      { date: '2021.08', title: '盐湖股份恢复上市 +306%', detail: '末日轮疯狂：题材补涨股登峰，鱼尾期资金情绪的极致', kind: 'landed', category: 'funds' },
      { date: '2021.09', title: '能耗双控拉闸限电', detail: '限产冲击供给预期，周期与新能源同步巨震，波动率骤升', kind: 'landed', category: 'policy' },
      { date: '2021.11', title: '锂价与板块指数同步赶顶', detail: '碳酸锂加速冲向 30 万 / 吨（最后的疯狂）；创业板指 11 月见顶，「涨价逻辑」从利好转为成本压力', kind: 'landed', category: 'sector' },
      { date: '2021.12', title: '中央经济工作会议「先立后破」+ 美联储转鹰', detail: '双碳纠偏弱化政策预期；Taper 加速，全球成长股估值承压', kind: 'landed', category: 'policy' },
      { date: '2022.01', title: '开年集体杀跌', detail: '1.28 宁德单日 -8%，创业板指单月 -12%；新能源基金净值深回撤，基民赎回与机构减仓互为因果（多杀多）', kind: 'landed', category: 'funds' },
      { date: '2022.03', title: '伦镍逼仓 + 碳酸锂破 50 万', detail: '原材料成本失控挤压中游盈利，叠加俄乌冲突——产业逻辑正式证伪', kind: 'landed', category: 'sector' },
      { date: '2022.03', title: '上海封控冲击供应链', detail: '宁德 4 月部分停产，特斯拉上海停摆；4.27 创业板 2180 阶段低点，本轮抱团清算完成', kind: 'landed', category: 'overseas' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: true },
      { dimension: '中军走势', diverged: true },
      { dimension: '媒体舆论', diverged: false },
      { dimension: '机构行为', diverged: true },
      { dimension: '散户情绪', diverged: false },
    ],
    trigger: '产能过剩 + 产业数据证伪（锂价、排产）+ 流动性收紧',
    review:
      '产业景气型抱团：瓦解不靠监管，靠产业数据自身证伪。' +
      '「四条件错配」（成交不新高 / 中军不新高 / 小票涨停占比 80%+ / 核心股无利空跌停）在本轮首次全部触发，成为此后鱼尾判定的模板。',
  },
  {
    id: 'ai-tech',
    name: '本轮科技 AI 抱团',
    short: '24–26',
    indexSymbol: 'sz399006',
    indexName: '创业板指',
    roundType: '机构抱团 + 情绪主线',
    collapseType: 'B',
    collapseLabel: 'B 类·2026.7 崩盘',
    status: '已瓦解（2026.7）',
    window: { start: '2024-09', peak: '2026-06', end: '2026-09' },
    span: '2024.09 – 至今',
    mainline: 'AI 算力 / 半导体',
    midCaps: '中际旭创、寒武纪、海光信息',
    macro: 'AI 产业叙事 · 机构拥挤 · 「924」行情后增量资金',
    rival: '大金融 / 红利阶段性轮动分流',
    stages: [
      { name: '启动期', start: '2024-09', end: '2025-03', tone: 's1', desc: '海外映射 + 国产替代叙事启动' },
      { name: '发酵主升', start: '2025-03', end: '2026-02', tone: 's2', desc: '业绩兑现（光模块等），机构持续超配' },
      { name: '高潮鱼尾', start: '2026-02', end: '2026-06', tone: 's3', desc: '小票乱飞、中军滞涨、板块成交不再新高、核心股间歇大跌' },
      { name: '退潮期', start: '2026-06', end: '2026-09', tone: 's4', desc: '兑现不及预期 → 集体大阴线，批量跌停' },
    ],
    events: [
      { date: '2024.09', title: '「924」行情启动', detail: '国新办发布会降准降息 + 互换便利 / 回购增持再贷款，政治局会议加码，指数放量暴涨', kind: 'landed', category: 'policy' },
      { date: '2024.10', title: '科技确立为主线', detail: '指数冲高回落后，AI 算力成为增量资金的主战场', kind: 'landed', category: 'funds' },
      { date: '2024.11', title: '美国大选落地', detail: '出口链扰动强化「自主可控」叙事，国产算力 / 半导体获资金集中', kind: 'landed', category: 'overseas' },
      { date: '2025.01', title: 'DeepSeek-R1 引爆国产 AI', detail: '低成本训练路线重估全球算力格局（英伟达单日 -17%），「国产平替」逻辑强化', kind: 'landed', category: 'sector' },
      { date: '2025.02', title: '阿里豪掷 AI 基建', detail: '宣布三年资本开支超过去十年总和，互联网大厂资本开支上修点亮业绩兑现路径', kind: 'landed', category: 'leader' },
      { date: '2025.03', title: '「人工智能+」写入政府工作报告', detail: '产业政策背书，主线从算力扩散到应用', kind: 'landed', category: 'policy' },
      { date: '2025.H1', title: '光模块业绩兑现', detail: '中际旭创等龙头净利数倍增长，机构超配持续加深——「业绩验证」环节完成', kind: 'landed', category: 'leader' },
      { date: '2025.10', title: '国产算力订单放量', detail: '订单落地把抱团推入最后主升（用户复盘口径）', kind: 'landed', category: 'sector' },
      { date: '2025.H2', title: '拥挤度走向极致', detail: '机构对算力链配置达历史级拥挤；涨停结构恶化——涨停集中于小票补涨、中军滞涨（复盘口径）', kind: 'landed', category: 'funds' },
      { date: '2026.04', title: '机构言行背离', detail: '头部机构悄然降仓而卖方研报仍密集看多——本轮最经典的鱼尾信号（复盘口径）', kind: 'landed', category: 'funds' },
      { date: '2026.05', title: '中军与成交额双不新高', detail: '算力龙头滞涨、板块成交额不再创新高、间歇出现核心股无利空大跌——四条件错配集齐（复盘口径）', kind: 'landed', category: 'leader' },
      { date: '2026.07', title: '集体大阴线确认退潮', detail: '板块单日集体重挫、批量跌停；创业板指自 6 月顶点回撤逾两成，抱团终结（用户复盘口径）', kind: 'landed', category: 'funds' },
    ],
    mismatch: [
      { dimension: '赚钱效应', diverged: true },
      { dimension: '中军走势', diverged: true },
      { dimension: '媒体舆论', diverged: true },
      { dimension: '机构行为', diverged: true },
      { dimension: '散户情绪', diverged: true },
    ],
    trigger: '产业兑现不及预期 + 机构拥挤筹码松动',
    review:
      '离当下最近的一轮：鱼尾期四条件全部触发（成交额不再创新高 / 中军停止创新高 / 80% 以上涨停来自小盘补涨 / 间歇出现核心股无利空跌停）。' +
      '批量跌停出现 = 确认退潮，属同步 / 滞后信号；后续同类形态应交给 V2 的涨停结构看板滚动跟踪。',
  },
];

/** 模式库页签的可复用规律卡片（复盘框架沉淀） */
export const BULL_PATTERNS: readonly { title: string; desc: string }[] = [
  {
    title: '抱团自增强循环',
    desc: '业绩验证 → 基金加仓 → 股价上涨 → 新基金发行 → 再加仓；一轮持续约 3–4 年，循环在「申购端枯竭」时到顶。',
  },
  {
    title: '瓦解信号五类',
    desc: '① 估值极值 ② 持仓集中度极值 ③ 流动性 / 利率拐点 ④ 产业景气拐点（业绩证伪）⑤ 监管转向；同时出现 ≥2 类即高危。',
  },
  {
    title: '瓦解三形态',
    desc: 'A 类：涨停萎缩 → 批量跌停（题材小票）；B 类：中军先滞涨 → 大跌 → 中后期批量跌停；C 类：几乎不跌停，权重阴跌见顶。',
  },
  {
    title: '鱼尾四条件（禁加仓线）',
    desc: '① 板块成交额不再创新高 ② 中军停止创新高 ③ 80%+ 涨停来自小盘补涨 ④ 间歇出现核心股无利空跌停。四条齐 = 高风险鱼尾区，不代表马上暴跌。',
  },
];

/** 四轮机构抱团的涨跌停看板预警能力对比（来源：豆包复盘框架） */
export const BULL_BOARD_CAPABILITY: readonly {
  round: string;
  ability: string;
  abilityLevel: 'poor' | 'fair' | 'good';
  weakness: string;
  leadingSignal: string;
}[] = [
  { round: '06–07 大金融', ability: '很差', abilityLevel: 'poor', weakness: '权重几乎不涨跌停', leadingSignal: '权重 K 线、流动性、信贷周期' },
  { round: '19–21 白酒', ability: '差', abilityLevel: 'poor', weakness: '涨停只来自小票，中军不跌停', leadingSignal: '茅指数、美债收益率、公募拥挤度' },
  { round: '21–22 新能源', ability: '中等偏上', abilityLevel: 'fair', weakness: '崩盘前不会批量跌停', leadingSignal: '中军、板块成交额、产业景气拐点' },
  { round: '本轮科技 AI', ability: '中等偏上', abilityLevel: 'fair', weakness: '鱼尾小票继续涨停制造假象', leadingSignal: '算力龙头 K 线、板块成交、筹码拥挤' },
];
